services:
  db:
    image: mysql:5.7
    command: 
      - --innodb-use-native-aio=0
      #- --init-file /data/application/init.sql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nginx-node-network
  node-app:
    build:
      context: .
      dockerfile: ./node/Dockerfile
    image: marceloxneves/node:latest
    container_name: node-app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    tty: true
    restart: always
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    #comentei para que a porta seja liberada apenas para o nginx
    # ports:
    #   - "3000:3000"
    networks:
      - nginx-node-network
  
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: marceloxneves/nginx:latest
    container_name: nginx
    entrypoint: dockerize -wait tcp://node-app:3000 -timeout 30s
    command: nginx -g 'daemon off;'
    restart: always
    depends_on:
      - node-app
    networks:
      - nginx-node-network
    ports:
      - "8080:80"
networks:
  nginx-node-network:
    driver: bridge