services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nginx-node-network
  node-app:
    build:
      context: .
      dockerfile: ./node/Dockerfile
    image: marceloxneves/node:latest
    container_name: node-app
    #entrypoint: dockerize -wait tcp://db:3306 -timeout 10s docker-entrypoint.sh
    tty: true
    restart: always
    depends_on:
      - db
    #comentei para que a porta seja liberada apenas para o nginx
    # ports:
    #   - "3000:3000"
    networks:
      - nginx-node-network
    volumes:
      - ./node:/usr/src/app
  
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: marceloxneves/nginx:latest
    container_name: nginx
    depends_on:
      - node-app
    networks:
      - nginx-node-network
    ports:
      - "8080:80"
networks:
  nginx-node-network:
    driver: bridge